SCREEN_TITLE = "componga"

SHAPE_TYPES = (
    "Blip",
    "ArrowPath",
    "ArrowStraight",
    "LineStraight",
    "Ellipse",
    "Rectangle",
    "Path",
)
SHAPE_TYPES_LOWER = list(map(lambda t: t.lower(), SHAPE_TYPES))
SHAPE_TYPES_UPPER = list(map(lambda t: t.upper(), SHAPE_TYPES))

DEFAULT_SHAPE = "ArrowStraight"
DEFAULT_SHAPE_LINE_WIDTH = 5
MIN_SHAPE_LINE_WIDTH = 1
MAX_SHAPE_LINE_WIDTH = 15
DEFAULT_SHAPE_COLOR = (1, 0, 0, 1)
DEFAULT_SHAPE_FADE_DURATION = 5.0

# Allowed keys must be included in the ones defined in kivy.core.window.Keyboard.keycodes
_KEYCODES = [
    # specials keys
    "backspace",
    "tab",
    "enter",
    "escape",
    "spacebar",
    "pageup",
    "pagedown",
    "end",
    "home",
    "left",
    "up",
    "right",
    "down",
    "insert",
    "delete",
    "print",
    "pause",
    # a-z keys
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    # 0-9 keys
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    # numpad
    "numpad0",
    "numpad1",
    "numpad2",
    "numpad3",
    "numpad4",
    "numpad5",
    "numpad6",
    "numpad7",
    "numpad8",
    "numpad9",
    "numpaddecimal",
    "numpaddivide",
    "numpadmul",
    "numpadsubstract",
    "numpadadd",
    "numpadenter",
    # F1-15
    "f1",
    "f2",
    "f3",
    "f4",
    "f5",
    "f6",
    "f7",
    "f8",
    "f9",
    "f10",
    "f11",
    "f12",
    "f13",
    "f14",
    "f15",
    # other keys
    "(",
    ")",
    "[",
    "]",
    "{",
    "}",
    ";",
    "=",
    "+",
    "-",
    "_",
    "/",
    "*",
    "?",
    "`",
    "~",
    "´",
    "¦",
    "\\",
    "|",
    '"',
    "'",
    ",",
    ".",
    "<",
    ">",
    "@",
    "!",
    "#",
    "$",
    "%",
    "^",
    "&",
    "¬",
    "¨",
]

DEFAULT_CONFIG_SECTIONS = [
    {
        "name": "shapes.attributes",
        "options": {
            "shape_type": DEFAULT_SHAPE,
            "shape_line_width": DEFAULT_SHAPE_LINE_WIDTH,
            "min_shape_line_width": MIN_SHAPE_LINE_WIDTH,
            "max_shape_line_width": MAX_SHAPE_LINE_WIDTH,
            "shape_color": DEFAULT_SHAPE_COLOR,
            "shape_fade_duration": DEFAULT_SHAPE_FADE_DURATION,
        },
    },
    {
        "name": "keyboard.shortcuts",
        "options": {
            "freeze": "f",
            "update_background": "u",
            "exit": "escape",
            "select_blip": "b",
            "select_arrow_path": "a",
            "select_arrow_straight": "s",
            "select_line_straight": "l",
            "select_ellipse": "o",
            "select_rectangle": "r",
            "select_path": "p",
        },
    },
    {
        "name": "keyboard.shortcuts.help",
        "options": {
            "freeze": "Disable shape fading",
            "update_background": "Refresh desktop image",
            "exit": "Exit Componga",
            "select_blip": "Select Blip tool",
            "select_arrow_path": "Select ArrowPath tool",
            "select_arrow_straight": "Select ArrowStraight tool",
            "select_line_straight": "Select LineStraight tool",
            "select_ellipse": "Select Ellipse tool",
            "select_rectangle": "Select Rectangle tool",
            "select_path": "Select Path tool",
        },
    },
]

CONFIG_PANEL_SHAPES_SECTIONS = [
    {"type": "title", "title": "Shapes Options"},
    {
        "type": "numeric",
        "title": "Min Shape Line Width",
        "desc": "Minimum width of the shape's line",
        "section": "shapes.attributes",
        "key": "min_shape_line_width",
    },
    {
        "type": "numeric",
        "title": "Max Shape Line Width",
        "desc": "Maximum width of the shape's line",
        "section": "shapes.attributes",
        "key": "max_shape_line_width",
    },
    {
        "type": "numeric",
        "title": "Shape Fade Duration",
        "desc": "Time interval until shape fades away",
        "section": "shapes.attributes",
        "key": "shape_fade_duration",
    },
]

CONFIG_PANEL_KEYBOARD_SECTIONS = [
    {"type": "title", "title": "Keyboard Shortcuts"},
    {
        "type": "options",
        "title": "Freeze",
        "desc": "Enable/Disable shape fading",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "freeze",
    },
    {
        "type": "options",
        "title": "Update Background",
        "desc": "Refresh desktop image",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "update_background",
    },
    {
        "type": "options",
        "title": "Blip",
        "desc": "Select Blip tool",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "select_blip",
    },
    {
        "type": "options",
        "title": "Arrow Path",
        "desc": "Select Arrow Path tool",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "select_arrow_path",
    },
    {
        "type": "options",
        "title": "Arrow Straight",
        "desc": "Select Arrow Straight tool",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "select_arrow_straight",
    },
    {
        "type": "options",
        "title": "Line Straight",
        "desc": "Select Line Straight tool",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "select_line_straight",
    },
    {
        "type": "options",
        "title": "Ellipse",
        "desc": "Select Ellipse tool",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "select_ellipse",
    },
    {
        "type": "options",
        "title": "Rectangle",
        "desc": "Select Rectangle tool",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "select_rectangle",
    },
    {
        "type": "options",
        "title": "Path",
        "desc": "Select Path tool",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "select_path",
    },
    {
        "type": "options",
        "title": "Exit",
        "desc": "Exit Componga",
        "options": _KEYCODES,
        "section": "keyboard.shortcuts",
        "key": "exit",
    },
]
